[김민정] 2023 GDSC Spring Novice Study - 1주차
dsc-sookmyung/2023-02-Spring-Novice-Study pull request #12
Opened 2023-11-07 12:06 UTC by GDSCMJ

## 👀 새롭게 배운 점

- 이번주는 spring보다는 처음 접해본 깃과 깃허브를 공부하는데 더 많은 시간을 들였습니다. (Spring도 처음이지만,,,)
여러 에러들을 접해보면서 조금씩 익숙해져 가는 것이 다행스럽게도 보였던 것 같습니다.
다음 주는 spring 공부에 더 많은 시간을 투자해 보려고 계획 중입니다.

## 📍 1주차 레퍼런스

* 스프링과 스프링 부트의 차이점

-스프링은 dependency에 대한 버전 관리 하나하나 해야함, 스프링 부트는 버전관리 자동.
-스프링은 모든 어노테이션과 빈 등록 설정 해야함, 스프링 부트는 application.properties, application.yml 파일에 설정하면 됨.
-스프링 부트는 스프링과는 달리 AutoConfiguration을 가지고 있음. 이 어노테이션으로 외부 라이브러리, 내장 톰캣 서버 등 실행 가능.
-스프링은 war 파일을 WAS 에 담아 배포, 스프링 부트는 내장 WAS를 가지고 있어서 jar 파일로 간편하게 배포 가능.

2023-11-07 15:04 UTC, GDSCMJ commented
@5jisoo 수정해서 올렸습니다! 감사합니다

2023-11-14 10:12 UTC, 5jisoo requested changes
전체 루트 폴더안에 있는 README.md가 아닌 자신의 개인 폴더의 README.md로 옮겨주시고, 원래 리드미는 복구해주세요!

2023-11-14 10:12 UTC, 5jisoo commented on README.md
> +## 1장 인텔리제이로 스프링부트 시작하기
현재 전체 루트 폴더의 리드미를 편집하신 것 같습니다. 확인부탁드립니다.

2023-11-14 10:53 UTC, GDSCMJ commented on README.md
> +## 1장 인텔리제이로 스프링부트 시작하기
수정하였습니다!

2023-11-15 15:46 UTC, 5jisoo approved these changes

2023-11-15 15:46 UTC, merged