[김세희] 2023 GDSC Spring Novice Study - 1주차
dsc-sookmyung/2023-02-Spring-Novice-Study pull request #7
Opened 2023-11-06 09:49 UTC by sehee0207

1주차 레퍼런스 과제 : https://velog.io/@sehee0207/SpringBoot-1%EC%A3%BC%EC%B0%A8-%EA%B3%BC%EC%A0%9C

초기 환경 설정에 오랜 시간이 걸렸다. 프로젝트만 10번 정도 만들었다가 지우는 과정에서
약간의 구글링을 통해 3.x 버전에서는 자바 17 이상, 2.x 버전에서는 자바 11 을 사용해줘야 한다는 걸 배웠다. 😅
이제 초기 환경 설정은 잘 할 수 있을 것 같다. 😗

롬복 설치 이후 변수 선언 부분에서 알 수 없는 오류가 떴었는데 인텔리제이 환경 설정을 바꿔주니 해결 되었다.
생각보다 설정할게 많고, 예민한 느낌이라 조금 어려웠지만 오류 없이 깔끔한 콘솔창을 보니 기분이 너무 좋았다 ...
다음주도 화이팅 😸

2023-11-06 15:20 UTC, 5jisoo reviewed
세희님 아직 1주차 실습이 모두 마무리되지 않은 것 같습니다.😥 
2장까지 실습 내용 확인 후 이 PR에 수정 커밋 날려주세요! 감사합니다.

2023-11-07 09:00 UTC, sehee0207 commented
안녕하세요! 혹시 build.gradle 파일 실습 말씀하시는 걸까요?
제가 지금 책이 없어서 어느 부분 실습을 덜 한건지 모르겠어서요!

2023-11-07 10:13 UTC, 5jisoo commented
네....?? 지금 없다는 말씀이시죠?
2장에 Controller 추가와 Test코드 작성 실습 책에 수록되어 있습니다!

2023-11-14 10:26 UTC, 5jisoo requested changes
아래 수정사항 확인해주세요~

2023-11-14 10:26 UTC, 5jisoo commented on 김세희/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/web/dto/HelloResponseDtoTest.java
> +    public void 롬복_기능_테스트(){
`@Test` 애노테이션이 생략되어 테스트 실행이 불가능 한 것 같습니다. 확인부탁드려요!

2023-11-15 07:06 UTC, sehee0207 commented on 김세희/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/web/dto/HelloResponseDtoTest.java
> +    public void 롬복_기능_테스트(){
수정했습니다!

2023-11-15 15:45 UTC, 5jisoo approved these changes

2023-11-15 15:45 UTC, merged